[package]
name = "neurarust-data"
version = "0.1.0"
edition = "2021"

[dependencies]
neurarust-core = { path = "../neurarust-core" }
rand = "0.8"

[dev-dependencies]
neurarust-core = { path = "../neurarust-core" } 