[package]
name = "neurarust-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neurarust-core = { path = "../neurarust-core" }
rand = "0.8"
num-traits = "0.2"
