[package]
name = "neurarust-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Core tensor library for NeuraRust"

[dependencies]
num-traits = "0.2"
rand = "0.8"
# neurarust-optim = { path = "../neurarust-optim" } # Removed to break cycle
thiserror = "1.0"
ndarray = "0.15" # Potentially useful for testing/comparison, optional?
# Add approx for floating point comparisons in tests
approx = { version = "0.5", optional = true }

[dev-dependencies]
# We might want approx specifically for dev tests
approx = "0.5"

[features]
default = []
# Example feature for conditional compilation later (e.g., GPU support)
# gpu = ["dep:cuda-bindings"]
